global:
  scrape_interval: 5s # 5秒ごとにデータを取得

scrape_configs:
  - job_name: "mikuops-backend"
    metrics_path: "/metrics"
    static_configs:
      - targets: ["backend:8000"] # Dockerネットワーク内のサービス名で指定